name: human packaging
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43104
title: the art of packaging objects and people
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d8eaf7'
    - '#2d3457'
    - '#b3c2df'
    - '#7381a3'
  brandStrength: 0.1875
  lightness: 0.09656268125399947
  saturation: 0.4768411349505186
  rhythmicContrast: 0.2723091479856521
purpose: []
