name: human packaging
favicon: null
layout_spectrum: 0.29004314076155424
typography_spectrum: 0.9786716885864735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.28511151135899127
  lightness: 0.09656268125399947
  saturation: 0.4768411349505186
  rhythmicContrast: 0.2723091479856521
purpose: []
